version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: data_ingestion_app
    environment:
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
    # Remove S3_ENDPOINT in prod so AWS SDK uses default
    command: ["./app"]
    volumes:
      - .:/app
    working_dir: /app